import { OptimizationResult } from '../types';

/**
 * Maps a programming language name to its standard file extension.
 */
export function getLanguageExtension(language: string): string {
  const l = (language || '').toLowerCase().trim();
  if (l.includes('typescript') || l === 'ts') return 'ts';
  if (l.includes('tsx')) return 'tsx';
  if (l.includes('javascript') || l === 'js') return 'js';
  if (l.includes('jsx')) return 'jsx';
  if (l.includes('python') || l === 'py') return 'py';
  if (l.includes('c++') || l.includes('cpp')) return 'cpp';
  if (l.includes('c#') || l.includes('cs') || l.includes('csharp')) return 'cs';
  if (l.includes('c') && !l.includes('css') && !l.includes('clojure')) return 'c';
  if (l.includes('java') && !l.includes('script')) return 'java';
  if (l.includes('rust') || l === 'rs') return 'rs';
  if (l.includes('go') || l.includes('golang')) return 'go';
  if (l.includes('sql') || l.includes('postgres') || l.includes('mysql')) return 'sql';
  if (l.includes('php')) return 'php';
  if (l.includes('ruby') || l.includes('rb')) return 'rb';
  if (l.includes('swift')) return 'swift';
  if (l.includes('kotlin') || l.includes('kt')) return 'kt';
  if (l.includes('scala')) return 'scala';
  if (l.includes('bash') || l.includes('sh') || l.includes('shell')) return 'sh';
  if (l.includes('html')) return 'html';
  if (l.includes('css')) return 'css';
  if (l.includes('json')) return 'json';
  if (l.includes('yaml') || l.includes('yml')) return 'yaml';
  return 'txt';
}

/**
 * Triggers a file download on the client machine.
 */
export function downloadFile(content: string, filename: string, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Generates a full markdown report suitable for documentation or GitHub PR descriptions.
 */
export function generateMarkdownReport(result: OptimizationResult): string {
  const dateStr = result.timestamp ? new Date(result.timestamp).toUTCString() : new Date().toUTCString();
  const ext = getLanguageExtension(result.language);

  return `# Code Optimization & Big-O Performance Report

**Generated on:** ${dateStr}  
**Language:** ${result.language}  
**Optimization Focus:** ${result.focus.toUpperCase()}  
**Estimated Speedup:** ${result.metrics.estimatedSpeedup}

---

## 📊 Performance & Complexity Comparison

| Metric | Suboptimal (Before) | Optimized (After) | Impact |
| :--- | :--- | :--- | :--- |
| **Time Complexity** | \`${result.metrics.timeComplexityBefore}\` | \`${result.metrics.timeComplexityAfter}\` | 🚀 Algorithmic Improvement |
| **Space Complexity** | \`${result.metrics.spaceComplexityBefore}\` | \`${result.metrics.spaceComplexityAfter}\` | 💾 Memory Footprint |
| **Readability Score** | \`${result.metrics.readabilityScoreBefore} / 10\` | \`${result.metrics.readabilityScoreAfter} / 10\` | 📖 Maintainability |
| **Speedup Factor** | Baseline (1.0x) | **${result.metrics.estimatedSpeedup}** | ⚡ Overall Runtime Gain |

---

## 🎯 Executive Summary
${result.summary}

---

## 🛠️ Key Architectural & Algorithmic Explanations

${result.explanations
  .map(
    (exp, idx) => `### ${idx + 1}. ${exp.title}
- **Category:** \`${exp.category}\` | **Impact:** **${exp.impact.toUpperCase()}**
- **Problem Identified:**  
  ${exp.problem}
- **Applied Solution:**  
  ${exp.solution}
- **Technical Deep-Dive:**  
  ${exp.technicalDeepDive}
`
  )
  .join('\n')}

---

## 💻 Optimized Source Code

\`\`\`${ext}
${result.optimizedCode}
\`\`\`

---

## 🔍 Original (Suboptimal) Code

\`\`\`${ext}
${result.originalCode}
\`\`\`

---

## 🧪 Testing Tips & Benchmarking Guidance
${result.benchmarksAndTestingTips && result.benchmarksAndTestingTips.length > 0
  ? result.benchmarksAndTestingTips.map((tip) => `- ${tip}`).join('\n')
  : '- Run benchmark suites with large input sizes ($N \\ge 10^5$) to measure algorithmic divergence.\n- Monitor GC pause duration and memory allocation profiles.'}

## ⚖️ Trade-offs & Caveats
${result.tradeoffsOrCaveats && result.tradeoffsOrCaveats.length > 0
  ? result.tradeoffsOrCaveats.map((c) => `- ${c}`).join('\n')
  : '- None reported.'}

---
*Report generated by Code Optimizer Pro with Gemini AI Engine.*
`;
}

/**
 * Unescapes literal \n, normalizes line breaks, and cleans markdown wrappers so that
 * the full multi-line code is always rendered with accurate line counts.
 */
export function normalizeFullSourceCode(codeStr: string): string {
  if (!codeStr || typeof codeStr !== 'string') return '';
  let normalized = codeStr;

  // Unescape literal \n or \r\n if the AI output contained raw escaped characters
  if (normalized.includes('\\n') && !normalized.includes('\n')) {
    normalized = normalized.replace(/\\r\\n/g, '\n').replace(/\\n/g, '\n').replace(/\\t/g, '\t');
  }

  // Strip wrapping markdown code fences if present (e.g. ```typescript ... ```)
  if (normalized.trim().startsWith('```')) {
    normalized = normalized.trim().replace(/^```[a-zA-Z0-9_-]*\s*\n?/, '').replace(/\n?```\s*$/, '');
  }

  return normalized;
}

/**
 * Robust clipboard copy function supporting modern Clipboard API with
 * seamless fallback to textarea execCommand for iframe and mobile sandboxes.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (!text) return false;
  const cleanText = normalizeFullSourceCode(text);

  // 1. Try modern navigator.clipboard
  try {
    if (navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {
      await navigator.clipboard.writeText(cleanText);
      return true;
    }
  } catch (err) {
    console.warn('[Clipboard] navigator.clipboard.writeText unavailable or restricted in iframe:', err);
  }

  // 2. Fallback using temporary textarea
  try {
    const textArea = document.createElement('textarea');
    textArea.value = cleanText;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    textArea.style.opacity = '0';
    textArea.setAttribute('readonly', '');
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    console.error('[Clipboard] execCommand copy fallback failed:', err);
    return false;
  }
}

/**
 * Generates a unified git-compatible patch/diff string.
 */
export function generateGitDiff(originalCode: string, optimizedCode: string, filename = 'code.src'): string {
  const origLines = originalCode.split('\n');
  const optLines = optimizedCode.split('\n');
  
  let diffText = `--- a/${filename}\n+++ b/${filename}\n@@ -1,${origLines.length} +1,${optLines.length} @@\n`;
  
  // Simple representation
  origLines.forEach((l) => {
    diffText += `-${l}\n`;
  });
  optLines.forEach((l) => {
    diffText += `+${l}\n`;
  });

  return diffText;
}
